### ISSUE TITLE
Unable to configure extension in Linux Mint Cinnamon 19

### ISSUE THREAD

**Issue by Naebulys** [germanfr/watermark-cinnamon#1]
Hello, 
I am using Linux Mint Cinnamon 19, but I am unable to configure the extension, and no watermark is appearing on my desktop. I've tried rebooting, but that doesn't help. I am sorry I can't give any more details :c

**Comment by germanfr** [comment]
Can you upload the `~/.xsession-errors` file? And what Cinnamon version are you on (`cinnamon --version`)?
